const data = [
    {
        id: 1,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',

    },
    {
        id: 2,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 3,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 4,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 5,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 6,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 7,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 8,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 9,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 10,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 11,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 12,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    {
        id: 13,
        packageName : 'Mini Land',
        price: '999',
        time: '6 months',
        status: 'Active',
        description: '',
    },
    
  
]

export default data